model: env(MODEL:openai/gpt-5-mini)
model_endpoint: env(MODEL_ENDPOINT:null)

seed: env(SEED:22)

fn_set: env(FN_SET:all)
feedback: env(FEEDBACK:false)
know_before_use: env(KNOW_BEFORE_USE:false)
notes_file: env(NOTES_FILE:null)

list_k: env(LIST_K:10)
search_top_k: env(SEARCH_TOP_K:10)
result_max_rows: env(RESULT_MAX_ROWS:10)
result_max_columns: env(RESULT_MAX_COLUMNS:10)

temperature: env(TEMPERATURE:1.0)
top_p: env(TOP_P:1.0)
reasoning_effort: env(REASONING_EFFORT:null)
reasoning_summary: env(REASONING_SUMMARY:null)
api: env(API:null)

knowledge_graphs:
  - kg: env(KG)
    endpoint: env(KG_ENDPOINT:null)
    entities_type: env(ENTITIES_TYPE:null)
    properties_type: env(PROPERTIES_TYPE:null)
    notes_file: env(KG_NOTES_FILE:null)

# note configuration
max_notes: env(MAX_NOTES:16)
max_note_length: env(MAX_NOTE_LENGTH:512)

num_rounds: env(NUM_ROUNDS:20)

questions_per_round: env(QUESTIONS_PER_ROUND:4)
